2022-05-05 15:28:23,437 INFO: Microblog startup [in D:\codeproject\PycharmProjects\microblog\app\__init__.py:36]
2022-05-05 15:29:06,148 INFO: Microblog startup [in D:\codeproject\PycharmProjects\microblog\app\__init__.py:36]
2022-05-05 20:49:15,366 INFO: Microblog startup [in D:\codeproject\PycharmProjects\microblog\app\__init__.py:41]
2022-05-05 20:49:49,030 ERROR: Exception on /reset_password_request [POST] [in D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\codeproject\PycharmProjects\microblog\app\routes.py", line 165, in reset_password_request
    send_password_reset_email(user)
NameError: name 'send_password_reset_email' is not defined
2022-05-05 20:50:03,283 INFO: Microblog startup [in D:\codeproject\PycharmProjects\microblog\app\__init__.py:41]
2022-05-05 20:50:05,362 ERROR: Exception on /reset_password_request [POST] [in D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\codeproject\PycharmProjects\microblog\app\routes.py", line 166, in reset_password_request
    send_password_reset_email(user)
  File "D:\codeproject\PycharmProjects\microblog\app\email.py", line 14, in send_password_reset_email
    token = user.get_reset_password_token()
AttributeError: 'User' object has no attribute 'get_reset_password_token'
2022-05-05 20:50:08,854 ERROR: Exception on /reset_password_request [POST] [in D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\codeproject\PycharmProjects\microblog\app\routes.py", line 166, in reset_password_request
    send_password_reset_email(user)
  File "D:\codeproject\PycharmProjects\microblog\app\email.py", line 14, in send_password_reset_email
    token = user.get_reset_password_token()
AttributeError: 'User' object has no attribute 'get_reset_password_token'
2022-05-05 21:03:38,802 INFO: Microblog startup [in D:\codeproject\PycharmProjects\microblog\app\__init__.py:41]
2022-05-05 21:03:46,639 ERROR: Exception on /reset_password_request [POST] [in D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\codeproject\PycharmProjects\microblog\app\routes.py", line 166, in reset_password_request
    send_password_reset_email(user)
  File "D:\codeproject\PycharmProjects\microblog\app\email.py", line 14, in send_password_reset_email
    token = user.get_reset_password_token()
  File "D:\codeproject\PycharmProjects\microblog\app\models.py", line 69, in get_reset_password_token
    {'reset_password':self.id, 'exp': time() + expires_in},
TypeError: unsupported operand type(s) for +: 'datetime.time' and 'int'
2022-05-05 21:05:33,555 INFO: Microblog startup [in D:\codeproject\PycharmProjects\microblog\app\__init__.py:41]
2022-05-05 21:05:37,227 ERROR: Exception on /reset_password_request [POST] [in D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\codeproject\PycharmProjects\microblog\app\routes.py", line 166, in reset_password_request
    send_password_reset_email(user)
  File "D:\codeproject\PycharmProjects\microblog\app\email.py", line 14, in send_password_reset_email
    token = user.get_reset_password_token()
  File "D:\codeproject\PycharmProjects\microblog\app\models.py", line 69, in get_reset_password_token
    return jwt.encode(
AttributeError: 'str' object has no attribute 'decode'
2022-05-05 21:06:03,351 INFO: Microblog startup [in D:\codeproject\PycharmProjects\microblog\app\__init__.py:41]
2022-05-05 21:06:05,748 ERROR: Exception on /reset_password_request [POST] [in D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\codeproject\PycharmProjects\microblog\app\routes.py", line 166, in reset_password_request
    send_password_reset_email(user)
  File "D:\codeproject\PycharmProjects\microblog\app\email.py", line 14, in send_password_reset_email
    token = user.get_reset_password_token()
  File "D:\codeproject\PycharmProjects\microblog\app\models.py", line 69, in get_reset_password_token
    return jwt.encode(
AttributeError: 'str' object has no attribute 'decode'
2022-05-05 21:09:45,446 INFO: Microblog startup [in D:\codeproject\PycharmProjects\microblog\app\__init__.py:41]
2022-05-05 21:09:52,764 ERROR: Exception on /reset_password_request [POST] [in D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\codeproject\PycharmProjects\microblog\app\routes.py", line 166, in reset_password_request
    send_password_reset_email(user)
  File "D:\codeproject\PycharmProjects\microblog\app\email.py", line 14, in send_password_reset_email
    token = user.get_reset_password_token()
  File "D:\codeproject\PycharmProjects\microblog\app\models.py", line 69, in get_reset_password_token
    return jwt.encode(
AttributeError: 'str' object has no attribute 'decode'
2022-05-05 21:21:25,608 INFO: Microblog startup [in D:\codeproject\PycharmProjects\microblog\app\__init__.py:41]
