2022-05-03 20:08:01,729 INFO: Microblog startup [in D:\codeproject\PycharmProjects\microblog\app\__init__.py:36]
2022-05-03 20:21:42,588 INFO: Microblog startup [in D:\codeproject\PycharmProjects\microblog\app\__init__.py:36]
2022-05-03 20:23:48,446 INFO: Microblog startup [in D:\codeproject\PycharmProjects\microblog\app\__init__.py:36]
2022-05-03 20:24:29,546 INFO: Microblog startup [in D:\codeproject\PycharmProjects\microblog\app\__init__.py:36]
2022-05-03 20:24:48,686 INFO: Microblog startup [in D:\codeproject\PycharmProjects\microblog\app\__init__.py:36]
2022-05-03 20:32:38,521 INFO: Microblog startup [in D:\codeproject\PycharmProjects\microblog\app\__init__.py:36]
2022-05-03 20:35:17,971 INFO: Microblog startup [in D:\codeproject\PycharmProjects\microblog\app\__init__.py:36]
2022-05-03 20:45:05,393 INFO: Microblog startup [in D:\codeproject\PycharmProjects\pythonProject4\app\__init__.py:36]
2022-05-03 20:54:08,947 INFO: Microblog startup [in D:\codeproject\PycharmProjects\microblog\app\__init__.py:36]
2022-05-03 21:57:43,045 INFO: Microblog startup [in D:\codeproject\PycharmProjects\microblog\app\__init__.py:36]
2022-05-03 21:57:49,963 INFO: Microblog startup [in D:\codeproject\PycharmProjects\microblog\app\__init__.py:36]
2022-05-04 19:50:29,350 INFO: Microblog startup [in D:\codeproject\PycharmProjects\microblog\app\__init__.py:36]
2022-05-04 19:50:34,930 ERROR: Exception on /user/zhangsan [GET] [in D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask_login\utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "D:\codeproject\PycharmProjects\microblog\app\routes.py", line 79, in user
    return render_template('user.html', user=user, posts=posts, form=form)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\templating.py", line 149, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\jinja2\environment.py", line 1071, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\jinja2\environment.py", line 1000, in get_template
    return self._load_template(name, globals)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\jinja2\environment.py", line 959, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\jinja2\loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\jinja2\environment.py", line 758, in compile
    self.handle_exception(source=source_hint)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\jinja2\environment.py", line 926, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\codeproject\PycharmProjects\microblog\app\templates\user.html", line 32, in template
    <form action="{{ url_for('unfollow', username=user.username }}" method="post">
jinja2.exceptions.TemplateSyntaxError: expected token ',', got 'unfollow'
2022-05-04 19:50:42,634 ERROR: Exception on /user/zhangsan [GET] [in D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask_login\utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "D:\codeproject\PycharmProjects\microblog\app\routes.py", line 79, in user
    return render_template('user.html', user=user, posts=posts, form=form)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\templating.py", line 149, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\jinja2\environment.py", line 1071, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\jinja2\environment.py", line 1000, in get_template
    return self._load_template(name, globals)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\jinja2\environment.py", line 959, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\jinja2\loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\jinja2\environment.py", line 758, in compile
    self.handle_exception(source=source_hint)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\jinja2\environment.py", line 926, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\codeproject\PycharmProjects\microblog\app\templates\user.html", line 32, in template
    <form action="{{ url_for('unfollow', username=user.username }}" method="post">
jinja2.exceptions.TemplateSyntaxError: expected token ',', got 'unfollow'
2022-05-04 19:50:51,161 ERROR: Exception on /user/zhangsan [GET] [in D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask_login\utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "D:\codeproject\PycharmProjects\microblog\app\routes.py", line 79, in user
    return render_template('user.html', user=user, posts=posts, form=form)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\templating.py", line 149, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\jinja2\environment.py", line 1071, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\jinja2\environment.py", line 1000, in get_template
    return self._load_template(name, globals)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\jinja2\environment.py", line 959, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\jinja2\loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\jinja2\environment.py", line 758, in compile
    self.handle_exception(source=source_hint)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\jinja2\environment.py", line 926, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\codeproject\PycharmProjects\microblog\app\templates\user.html", line 32, in template
    <form action="{{ url_for('unfollow', username=user.username }}" method="post">
jinja2.exceptions.TemplateSyntaxError: expected token ',', got 'unfollow'
