2022-05-04 21:46:11,701 ERROR: Exception on /index [POST] [in D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask_login\utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "D:\codeproject\PycharmProjects\microblog\app\routes.py", line 20, in index
    post = Post(body=form.post.data, author=current_user)
  File "<string>", line 4, in __init__
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\sqlalchemy\orm\state.py", line 480, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\sqlalchemy\util\langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\sqlalchemy\util\compat.py", line 207, in raise_
    raise exception
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\sqlalchemy\orm\state.py", line 477, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\sqlalchemy\orm\decl_base.py", line 1163, in _declarative_constructor
    raise TypeError(
TypeError: 'author' is an invalid keyword argument for Post
2022-05-04 21:47:44,958 INFO: Microblog startup [in D:\codeproject\PycharmProjects\microblog\app\__init__.py:36]
2022-05-04 21:48:32,241 ERROR: Exception on / [POST] [in D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask_login\utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "D:\codeproject\PycharmProjects\microblog\app\routes.py", line 20, in index
    post = Post(body=form.post.data, author=current_user)
  File "<string>", line 4, in __init__
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\sqlalchemy\orm\state.py", line 480, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\sqlalchemy\util\langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\sqlalchemy\util\compat.py", line 207, in raise_
    raise exception
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\sqlalchemy\orm\state.py", line 477, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\sqlalchemy\orm\decl_base.py", line 1163, in _declarative_constructor
    raise TypeError(
TypeError: 'author' is an invalid keyword argument for Post
2022-05-04 21:48:49,609 INFO: Microblog startup [in D:\codeproject\PycharmProjects\microblog\app\__init__.py:36]
2022-05-04 21:49:11,424 INFO: Microblog startup [in D:\codeproject\PycharmProjects\microblog\app\__init__.py:36]
2022-05-04 21:49:35,650 ERROR: Exception on / [POST] [in D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask_login\utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "D:\codeproject\PycharmProjects\microblog\app\routes.py", line 20, in index
    post = Post(body=form.post.data, author=current_user)
  File "<string>", line 4, in __init__
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\sqlalchemy\orm\state.py", line 480, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\sqlalchemy\util\langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\sqlalchemy\util\compat.py", line 207, in raise_
    raise exception
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\sqlalchemy\orm\state.py", line 477, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\sqlalchemy\orm\decl_base.py", line 1163, in _declarative_constructor
    raise TypeError(
TypeError: 'author' is an invalid keyword argument for Post
2022-05-04 21:49:54,243 INFO: Microblog startup [in D:\codeproject\PycharmProjects\microblog\app\__init__.py:36]
2022-05-04 21:50:19,086 ERROR: Exception on / [POST] [in D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask_login\utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "D:\codeproject\PycharmProjects\microblog\app\routes.py", line 20, in index
    post = Post(body=form.post.data, author=current_user)
  File "<string>", line 4, in __init__
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\sqlalchemy\orm\state.py", line 480, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\sqlalchemy\util\langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\sqlalchemy\util\compat.py", line 207, in raise_
    raise exception
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\sqlalchemy\orm\state.py", line 477, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\sqlalchemy\orm\decl_base.py", line 1163, in _declarative_constructor
    raise TypeError(
TypeError: 'author' is an invalid keyword argument for Post
2022-05-04 21:50:26,793 INFO: Microblog startup [in D:\codeproject\PycharmProjects\microblog\app\__init__.py:36]
