2022-05-04 21:51:08,618 ERROR: Exception on / [POST] [in D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask_login\utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "D:\codeproject\PycharmProjects\microblog\app\routes.py", line 20, in index
    post = Post(body=form.post.data, author=current_user)
  File "<string>", line 4, in __init__
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\sqlalchemy\orm\state.py", line 480, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\sqlalchemy\util\langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\sqlalchemy\util\compat.py", line 207, in raise_
    raise exception
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\sqlalchemy\orm\state.py", line 477, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\sqlalchemy\orm\decl_base.py", line 1163, in _declarative_constructor
    raise TypeError(
TypeError: 'author' is an invalid keyword argument for Post
2022-05-04 21:59:43,610 INFO: Microblog startup [in D:\codeproject\PycharmProjects\microblog\app\__init__.py:36]
2022-05-04 21:59:50,331 ERROR: Exception on / [POST] [in D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask_login\utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "D:\codeproject\PycharmProjects\microblog\app\routes.py", line 20, in index
    post = Post(body=form.post.data, author=current_user)
  File "<string>", line 4, in __init__
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\sqlalchemy\orm\state.py", line 480, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\sqlalchemy\util\langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\sqlalchemy\util\compat.py", line 207, in raise_
    raise exception
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\sqlalchemy\orm\state.py", line 477, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\sqlalchemy\orm\decl_base.py", line 1163, in _declarative_constructor
    raise TypeError(
TypeError: 'author' is an invalid keyword argument for Post
2022-05-04 22:01:47,450 INFO: Microblog startup [in D:\codeproject\PycharmProjects\microblog\app\__init__.py:36]
2022-05-05 14:07:53,344 INFO: Microblog startup [in D:\codeproject\PycharmProjects\microblog\app\__init__.py:36]
2022-05-05 14:35:50,349 INFO: Microblog startup [in D:\codeproject\PycharmProjects\microblog\app\__init__.py:36]
2022-05-05 15:07:01,701 INFO: Microblog startup [in D:\codeproject\PycharmProjects\microblog\app\__init__.py:36]
2022-05-05 15:07:03,455 ERROR: Exception on /index [GET] [in D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask_login\utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "D:\codeproject\PycharmProjects\microblog\app\routes.py", line 29, in index
    return render_template('index.html', title='Home Page', posts=posts.items, form=form,
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\templating.py", line 149, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\jinja2\environment.py", line 1071, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\jinja2\environment.py", line 1000, in get_template
    return self._load_template(name, globals)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\jinja2\environment.py", line 959, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\jinja2\loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\jinja2\environment.py", line 758, in compile
    self.handle_exception(source=source_hint)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\jinja2\environment.py", line 926, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\codeproject\PycharmProjects\microblog\app\templates\index.html", line 27, in template
    {% endblock %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endblock'. You probably made a nesting mistake. Jinja is expecting this tag, but currently looking for 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.
2022-05-05 15:08:54,761 INFO: Microblog startup [in D:\codeproject\PycharmProjects\microblog\app\__init__.py:36]
2022-05-05 15:26:54,825 INFO: Microblog startup [in D:\codeproject\PycharmProjects\microblog\app\__init__.py:36]
2022-05-05 15:27:00,323 ERROR: Exception on /user/wangwu [GET] [in D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask_login\utils.py", line 303, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "D:\codeproject\PycharmProjects\microblog\app\routes.py", line 80, in user
    return render_template('user.html', user=user, posts=posts.items, next_url=next_url, prev_url=prev_url)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\templating.py", line 149, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\jinja2\environment.py", line 1071, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\jinja2\environment.py", line 1000, in get_template
    return self._load_template(name, globals)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\jinja2\environment.py", line 959, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\jinja2\loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\jinja2\environment.py", line 758, in compile
    self.handle_exception(source=source_hint)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\jinja2\environment.py", line 926, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\codeproject\PycharmProjects\microblog\app\templates\user.html", line 49, in template
    {% endblock %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endblock'. You probably made a nesting mistake. Jinja is expecting this tag, but currently looking for 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.
