2022-05-05 21:21:32,909 ERROR: Exception on /reset_password_request [POST] [in D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\codeproject\PycharmProjects\microblog\app\routes.py", line 166, in reset_password_request
    send_password_reset_email(user)
  File "D:\codeproject\PycharmProjects\microblog\app\email.py", line 14, in send_password_reset_email
    token = user.get_reset_password_token()
  File "D:\codeproject\PycharmProjects\microblog\app\models.py", line 73, in get_reset_password_token
    return test.decode('utf-8')
AttributeError: 'str' object has no attribute 'decode'
2022-05-05 21:25:46,874 INFO: Microblog startup [in D:\codeproject\PycharmProjects\microblog\app\__init__.py:41]
2022-05-05 21:25:52,136 ERROR: Exception on /reset_password_request [POST] [in D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\codeproject\PycharmProjects\microblog\app\routes.py", line 166, in reset_password_request
    send_password_reset_email(user)
  File "D:\codeproject\PycharmProjects\microblog\app\email.py", line 16, in send_password_reset_email
    sender=app.config['MAIL_USERNAME'],
KeyError: 'MAIL_USERNAME'
2022-05-05 21:34:40,049 INFO: Microblog startup [in D:\codeproject\PycharmProjects\microblog\app\__init__.py:41]
2022-05-05 21:34:50,552 ERROR: Exception on /reset_password_request [POST] [in D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\codeproject\PycharmProjects\microblog\app\routes.py", line 166, in reset_password_request
    send_password_reset_email(user)
  File "D:\codeproject\PycharmProjects\microblog\app\email.py", line 16, in send_password_reset_email
    sender=app.config['MAIL_USERNAME'],
KeyError: 'MAIL_USERNAME'
2022-05-05 21:35:56,556 INFO: Microblog startup [in D:\codeproject\PycharmProjects\microblog\app\__init__.py:41]
2022-05-05 21:36:35,213 ERROR: Exception on /reset_password/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyZXNldF9wYXNzd29yZCI6MSwiZXhwIjoxNjUxNzU4MzU5LjcxOTIyNzN9.9HzZUe83zQvcBYQeSDgx0C-hQ4otPCZn_vhxmrMIn_Y [GET] [in D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\codeproject\PycharmProjects\microblog\app\routes.py", line 180, in reset_password
    form = ResetPasswordForm()
NameError: name 'ResetPasswordForm' is not defined
2022-05-05 21:37:03,145 INFO: Microblog startup [in D:\codeproject\PycharmProjects\microblog\app\__init__.py:41]
2022-05-05 21:37:16,144 ERROR: Exception on /reset_password/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyZXNldF9wYXNzd29yZCI6MSwiZXhwIjoxNjUxNzU4NDI4Ljc3NjkyNDR9.SDSDU5IlLGXUbLHP8zOX8hjkxIB2vF2E0xWAMyrhP7k [GET] [in D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\codeproject\PycharmProjects\microblog\app\routes.py", line 187, in reset_password
    return render_template('reset_password.html', form=form)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\flask\templating.py", line 149, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\jinja2\environment.py", line 1071, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\jinja2\environment.py", line 1000, in get_template
    return self._load_template(name, globals)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\jinja2\environment.py", line 959, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\jinja2\loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\jinja2\environment.py", line 758, in compile
    self.handle_exception(source=source_hint)
  File "D:\download\anaconda3\envs\pytorch\lib\site-packages\jinja2\environment.py", line 926, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\codeproject\PycharmProjects\microblog\app\templates\reset_password.html", line 21, in template
    <p>{{ form.submit() }}</p>
jinja2.exceptions.TemplateSyntaxError: Unexpected end of template. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2022-05-05 21:37:42,435 INFO: Microblog startup [in D:\codeproject\PycharmProjects\microblog\app\__init__.py:41]
2022-05-05 21:46:09,816 INFO: Microblog startup [in D:\codeproject\PycharmProjects\microblog\app\__init__.py:41]
2022-05-05 21:46:52,681 INFO: Microblog startup [in D:\codeproject\PycharmProjects\microblog\app\__init__.py:41]
2022-05-05 21:47:18,945 INFO: Microblog startup [in D:\codeproject\PycharmProjects\microblog\app\__init__.py:41]
2022-05-06 20:02:41,813 INFO: Microblog startup [in D:\codeproject\PycharmProjects\microblog\app\__init__.py:43]
2022-05-06 20:09:17,601 INFO: Microblog startup [in D:\codeproject\PycharmProjects\microblog\app\__init__.py:43]
